<?php

$maps = [
    'en' => [
        "The Reef",
        "Musselforge Fitness",
        "Starfish Mainstage",
        "Humpback Pump Track",
        "Inkblot Art Academy",
        "Sturgeon Shipyard",
        "Moray Towers",
        "Port Mackerel",
        "Manta Maria",
        "Kelp Dome",
        "Snapper Canal",
        "Blackbelly Skatepark",
        "MakoMart",
        "Walleye Warehouse",
        "Shellendorf Institute",
        "Arowana Mall",
        "Goby Arena",
        "Piranha Pit",
        "Camp Triggerfish",
        "Wahoo World",
        "New Albacore Hotel",
        "Ancho-V Games",
        "Skipper Pavilion"
    ],
    'jp' => [
        "バッテラストリート",
        "フジツボスポーツクラブ",
        "ガンガゼ野外音楽堂",
        "コンブトラック",
        "海女美術大学",
        "チョウザメ造船",
        "タチウオパーキング",
        "ホッケふ頭",
        "マンタマリア号",
        "モズク農園",
        "エンガワ河川敷",
        "Bバスパーク",
        "ザトウマーケット",
        "ハコフグ倉庫",
        "デボン海洋博物館",
        "アロワナモール",
        "アジフライスタジアム",
        "ショッツル鉱山",
        "モンガラキャンプ場",
        "スメーシーワールド",
        "ホテルニューオートロ",
        "アンチョビットゲームズ",
        "ムツゴ楼"
    ],
    'zh' => [
        "鯖魚壽司街道",
        "藤壺攀岩場",
        "海膽野外音樂堂",
        "昆布賽車道",
        "海女藝術大學",
        "鱘魚造船廠",
        "白帶魚停車場",
        "多線魚碼頭",
        "蝙魟瑪麗亞號",
        "海藴農園",
        "緣側河川",
        "黑鱸魚滑板公園",
        "座頭鯨超市",
        "箱河豚倉庫",
        "泥盆紀海洋博物館",
        "骨舌魚商店街",
        "炸竹莢魚體育館",
        "鹽魚汁礦山",
        "鱗魨露營場",
        "醋飯遊樂園",
        "新大脂飯店",
        "鯷魚遊戲室",
        "彈塗魚樓"
    ]
];