<?php

$weapons = [
    'en' => [
        "Sploosh-o-matic",
        "Neo Sploosh-o-matic",
        "Sploosh-o-matic 7",
        "Splattershot Jr.",
        "Custom Splattershot Jr.",
        "Kensa Splattershot Jr.",
        "Splash-o-matic",
        "Neo Splash-o-matic",
        "Aerospray MG",
        "Aerospray RG",
        "Aerospray PG",
        "Splattershot",
        "Tentatek Splattershot",
        "Kensa Splattershot",
        "Hero Shot Replica",
        "Octo Shot Replica",
        ".52 Gal",
        ".52 Gal Deco",
        "Kensa .52 Gal",
        "N-ZAP '85",
        "N-ZAP '89",
        "N-ZAP '83",
        "Splattershot Pro",
        "Forge Splattershot Pro",
        "Kensa Splattershot Pro",
        ".96 Gal",
        ".96 Gal Deco",
        "Jet Squelcher",
        "Custom Jet Squelcher",
        "Luna Blaster",
        "Luna Blaster Neo",
        "Kensa Luna Blaster",
        "Blaster",
        "Custom Blaster",
        "Hero Blaster Replica",
        "Range Blaster",
        "Custom Range Blaster",
        "Grim Range Blaster",
        "Clash Blaster",
        "Clash Blaster Neo",
        "Rapid Blaster",
        "Rapid Blaster Deco",
        "Kensa Rapid Blaster",
        "Rapid Blaster Pro",
        "Rapid Blaster Pro Deco",
        "L-3 Nozzlenose",
        "L-3 Nozzlenose D",
        "Kensa L-3 Nozzlenose",
        "H-3 Nozzlenose",
        "H-3 Nozzlenose D",
        "Cherry H-3 Nozzlenose",
        "Squeezer",
        "Foil Squeezer",
        "Carbon Roller",
        "Carbon Roller Deco",
        "Splat Roller",
        "Krak-On Splat Roller",
        "Kensa Splat Roller",
        "Hero Roller Replica",
        "Dynamo Roller",
        "Gold Dynamo Roller",
        "Kensa Dynamo Roller",
        "Flingza Roller",
        "Foil Flingza Roller",
        "Inkbrush",
        "Inkbrush Nouveau",
        "Permanent Inkbrush",
        "Octobrush",
        "Octobrush Nouveau",
        "Herobrush Replica",
        "Kensa Octobrush",
        "Classic Squiffer",
        "New Squiffer",
        "Fresh Squiffer",
        "Splat Charger",
        "Firefin Splat Charger",
        "Kensa Charger",
        "Hero Charger Replica",
        "Splatterscope",
        "Firefin Splatterscope",
        "Kensa Splatterscope",
        "E-liter 4K",
        "Custom E-liter 4K",
        "E-liter 4K Scope",
        "Custom E-liter 4K Scope",
        "Bamboozler 14 Mk I",
        "Bamboozler 14 Mk II",
        "Bamboozler 14 Mk III",
        "Goo Tuber",
        "Custom Goo Tuber",
        "Slosher",
        "Slosher Deco",
        "Soda Slosher",
        "Hero Slosher Replica",
        "Tri-Slosher",
        "Tri-Slosher Nouveau",
        "Sloshing Machine",
        "Sloshing Machine Neo",
        "Kensa Sloshing Machine",
        "Bloblobber",
        "Bloblobber Deco",
        "Explosher",
        "Custom Explosher",
        "Mini Splatling",
        "Zink Mini Splatling",
        "Kensa Mini Splatling",
        "Heavy Splatling",
        "Heavy Splatling Deco",
        "Heavy Splatling Remix",
        "Hero Splatling Replica",
        "Hydra Splatling",
        "Custom Hydra Splatling",
        "Ballpoint Splatling",
        "Ballpoint Splatling Nouveau",
        "Nautilus 47",
        "Nautilus 79",
        "Dapple Dualies",
        "Dapple Dualies Nouveau",
        "Clear Dapple Dualies",
        "Splat Dualies",
        "Enperry Splat Dualies",
        "Kensa Splat Dualies",
        "Hero Dualie Replicas",
        "Glooga Dualies",
        "Glooga Dualies Deco",
        "Kensa Glooga Dualies",
        "Dualie Squelchers",
        "Custom Dualie Squelchers",
        "Dark Tetra Dualies",
        "Light Tetra Dualies",
        "Splat Brella",
        "Sorella Brella",
        "Hero Brella Replica",
        "Tenta Brella",
        "Tenta Sorella Brella",
        "Tenta Camo Brella",
        "Undercover Brella",
        "Undercover Sorella Brella",
        "Kensa Undercover Brella"
    ],
    'jp' => [
        "ボールドマーカー",
        "ボールドマーカーネオ",
        "ボールドマーカー7",
        "わかばシューター",
        "もみじシューター",
        "おちばシューター",
        "シャープマーカー",
        "シャープマーカーネオ",
        "プロモデラー",
        "プロモデラー",
        "プロモデラーPG",
        "スプラシューター",
        "スプラシューターコラボ",
        "スプラシューターベッチュー",
        "ヒーローシューター レプリカ",
        "オクタシューター レプリカ",
        ".52ガロン",
        ".52ガロンデコ",
        ".52ガロンベッチュー",
        "N-ZAP85",
        "N-ZAP89",
        "N-ZAP83",
        "プライムシューター",
        "プライムシューターコラボ",
        "プライムシューターベッチュー",
        ".96ガロン",
        ".96ガロンデコ",
        "ジェットスイーパー",
        "ジェットスイーパーカスタム",
        "ノヴァブラスター",
        "ノヴァブラスターネオ",
        "ノヴァブラスターベッチュー",
        "ホットブラスター",
        "ホットブラスターカスタム",
        "ヒーローブラスターレプリカ",
        "ロングブラスター",
        "ロングブラスターカスタム",
        "ロングブラスターネクロ",
        "クラッシュブラスター",
        "クラッシュブラスターネオ",
        "ラピッドブラスター",
        "ラピッドブラスターデコ",
        "ラピッドブラスターベッチュー",
        "Rブラスターエリート",
        "Rブラスターエリートデコ",
        "L3リールガン",
        "L3リールガンD",
        "L3リールガンベッチュー",
        "H3リールガン",
        "H3リールガンD",
        "H3リールガンチェリー",
        "ボトルガイザー",
        "ボトルガイザーフォイル",
        "カーボンローラー",
        "カーボンローラーデコ",
        "スプラローラー",
        "スプラローラーコラボ",
        "スプラローラーベッチュー",
        "ヒーローローラーレプリカ",
        "ダイナモローラー",
        "ダイナモローラーテスラ",
        "ダイナモローラーベッチュー",
        "ヴァリアブルローラー",
        "ヴァリアブルローラーフォイル",
        "パブロ",
        "パブロ・ヒュー",
        "パーマネント・パブロ",
        "ホクサイ",
        "ホクサイ・ヒュー",
        "ヒーローブラシレプリカ",
        "ホクサイベッチュー",
        "スクイックリンα",
        "スクイックリンβ",
        "スクイックリンγ",
        "スプラチャージャー",
        "スプラチャージャー コラボ",
        "スプラチャージャーベッチュー",
        "ヒーローチャージャーレプリカ",
        "スプラスコープ",
        "スプラスコープ コラボ",
        "スプラスコープベッチュー",
        "リッター4K",
        "リッター4kカスタム",
        "4Kスコープ",
        "4kスコープカスタム",
        "14式竹筒銃・甲",
        "14式竹筒銃・乙",
        "14式竹筒銃・丙",
        "ソイチューバー",
        "ソイチューバーカスタム",
        "バケットスロッシャー",
        "バケットスロッシャーデコ",
        "バケットスロッシャーソーダ",
        "ヒーロースロッシャーレプリカ",
        "ヒッセン",
        "ヒッセン・ヒュー",
        "スクリュースロッシャー",
        "スクリュースロッシャーネオ",
        "スクリュースロッシャーベッチュー",
        "オーバーフロッシャー",
        "オーバーフロッシャーデコ",
        "エクスプロッシャー",
        "エクスプロッシャーカスタム",
        "スプラスピナー",
        "スプラスピナーコラボ",
        "スプラスピナーベッチュー",
        "バレルスピナー",
        "バレルスピナーデコ",
        "バレルスピナーリミックス",
        "ヒーロースピナーレプリカ",
        "ハイドラント",
        "ハイドラントカスタム",
        "クーゲルシュライバー",
        "クーゲルシュライバー・ヒュー",
        "ノーチラス47",
        "ノーチラス79",
        "スパッタリー",
        "スパッタリー・ヒュー",
        "スパッタリークリア",
        "スプラマニューバー",
        "スプラマニューバーコラボ",
        "スプラマニューバーベッチュー",
        "ヒーローマニューバーレプリカ",
        "ケルビン525",
        "ケルビン525デコ",
        "ケルビン525ベッチュー",
        "デュアルスイーパー",
        "デュアルスイーパーカスタム",
        "クアッドホッパーブラック",
        "クアッドホッパーホワイト",
        "パラシェルター",
        "パラシェルターソレーラ",
        "ヒーローシェルターレプリカ",
        "キャンピングシェルター",
        "キャンピングシェルターソレーラ",
        "キャンピングシェルターカーモ",
        "スパイガジェット",
        "スパイガジェットソレーラ",
        "スパイガジェットベッチュー"
    ],
    'zh' => [
        "無印雷神",
        "導彈雷神",
        "槌子雷神",
        "初始若葉",
        "雨若葉",
        "黑若葉",
        "無印針槍",
        "水球針槍",
        "銀噴",
        "金噴",
        "銅噴",
        "無印壽司",
        "背包壽司",
        "黑壽司",
        "英雄壽司",
        "章魚壽司",
        "無印 .52",
        "水刀 .52",
        "黑 .52",
        "黑 ZAP",
        "橘 ZAP",
        "紅 ZAP",
        "無印 P",
        "泡泡 P",
        "黑 P",
        "無印 .96",
        "超落 .96",
        "無印洗車槍",
        "水刀洗車槍",
        "無印 Nova",
        "黏彈 Rush Nova",
        "黑 Nova",
        "無印短爆",
        "背包短爆",
        "英雄短爆",
        "無印長爆",
        "泡泡長爆",
        "綠長爆",
        "無印蠟筆",
        "導彈蠟筆",
        "無印短拉比",
        "背包短拉比",
        "黑拉比",
        "無印長拉比",
        "裝甲長拉比",
        "無印 L3",
        "背包 L3",
        "黑 L3",
        "無印 H3",
        "裝甲 H3",
        "紅 H3",
        "無印香檳",
        "泡泡香檳",
        "無印輕滾",
        "小雞 Rush 輕滾",
        "無印中滾",
        "倉鼠球中滾",
        "黑中滾",
        "英雄中滾",
        "無印重滾",
        "裝甲重滾",
        "黑重滾",
        "無印鋼筆",
        "導彈鋼筆",
        "無印巴布羅",
        "倉鼠球巴布羅",
        "裝甲巴布羅",
        "無印北齋",
        "導彈北齋",
        "英雄北齋",
        "槌子北齋",
        "裝甲清潔劑",
        "倉鼠球清潔劑",
        "紅清潔劑",
        "無印中狙",
        "黏彈 Rush 中狙",
        "黑中狙",
        "英雄中狙",
        "無印鏡中狙",
        "黏彈 Rush 鏡中狙",
        "黑鏡中狙",
        "無印 4K",
        "泡泡 4K",
        "無印鏡 4K",
        "泡泡鏡 4K",
        "無印竹狙",
        "水球 Rush 竹狙",
        "泡泡竹狙",
        "無印油管",
        "背包油管",
        "無印水桶",
        "倉鼠球水桶",
        "蘇打桶",
        "英雄水桶",
        "無印筆洗",
        "雨筆洗",
        "無印洗衣機",
        "飯糰 Rush 洗衣機",
        "黑洗衣機",
        "無印浴缸",
        "黏彈 Rush 浴缸",
        "無印重桶",
        "倉鼠球重桶",
        "無印輕格",
        "雨輕格",
        "黑輕格",
        "無印中格",
        "泡泡中格",
        "讚氣彈中格",
        "英雄中格",
        "無印重格",
        "裝甲重格",
        "無印筆格",
        "雨筆格",
        "無印鸚鵡螺",
        "背包鸚鵡螺",
        "紅牙刷",
        "藍牙刷",
        "白牙刷",
        "無印雙槍",
        "金雙槍",
        "黑雙槍",
        "英雄雙槍",
        "藍 525",
        "黃 525",
        "黑 525",
        "無印紅雙",
        "雨紅雙",
        "無印四翻",
        "小雞 Rush 四翻",
        "無印中傘",
        "飯糰 Rush 中傘",
        "英雄中傘",
        "無印露營傘",
        "冰壺 Rush 露營傘",
        "槌子露營傘",
        "無印間諜傘",
        "倉鼠球間諜傘",
        "白間諜傘"
    ],
];
